const swaggerAutogen = require('swagger-autogen')()
const doc = {
    info: {
        version: "1.0.0",
        title: "Homework",
        description: "Documentation automatically generated by the <b>swagger-autogen</b> module."
    },
    host: "localhost:3000",
    definitions: {
        User: {
            $email: "johnnyD0e@gmail.com",
            $password: "P4ssword",
        },
        Todo: {
            $name: "Clean the room",
            $deadline: "2022-11-11",
            $score: 1
        }
    }
}

const outputFile = './swagger-output.json'
const endpointsFiles = ['./app.js']

swaggerAutogen(outputFile, endpointsFiles, doc).then(() => {
    require('./bin/www')           
})